package estisharatibussiness.users.com.DataClassHelperMehtods.Chat

data class DataUserMessageFireStore(val dataUserFireStore: DataUserFireStore,val messagesArrayList: ArrayList<DataMessageFireStore>)